# Filebeat input setup for 4 different types of services
filebeat.inputs:
  - type: log
    id: app-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/app.log
    json.keys_under_root: true
    json.overwrite_keys: true
    fields_under_root: true
    clean_inactive: 25h
    ignore_older: 24h

  - type: log
    id: auth-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/auth.log
    json.keys_under_root: true
    json.overwrite_keys: true
    fields_under_root: true
    clean_inactive: 25h
    ignore_older: 24h

  - type: log
    id: payment-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/payment.log
    json.keys_under_root: true
    json.overwrite_keys: true
    fields_under_root: true
    clean_inactive: 25h
    ignore_older: 24h

  - type: log
    id: sql-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/sql.log
    json.keys_under_root: true
    json.overwrite_keys: true
    fields_under_root: true
    clean_inactive: 25h
    ignore_older: 24h

# Output kafka configuration
output.kafka:
  hosts: ["kafka:9092"]
  topic: "logs"
  codec.json:
    pretty: false 
